frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js
The responsiveness is well working. The input bars are responsive with respect to the syntaxMeets logo
=> The input bars has been made responsive

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Fixes issue #27.
Let me know any further changes required.
=> 🚀[Feat]:Github issue template added

CONTRIBUTING.md
Updated CONTRIBUTING.MD file with all the guidelines regarding open source contribution.
=> All the Guidelines added

backend/server/index.js, frontend/syntaxmeets/package-lock.json, frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js, frontend/syntaxmeets/src/components/SyntaxRoom/SyntaxRoom.js
=> Fixed Issue : Room only shows updated content after first change

backend/server/index.js, backend/server/package-lock.json, backend/server/package.json, frontend/syntaxmeets/src/components/SyntaxRoom/SyntaxRoom.js
Cors is Resolved as of now, but we need to take care from the frontend side as well. as of now, it's working well. 
Update some Dep versions.
=> CORS Resolved

frontend/syntaxmeets/package-lock.json, frontend/syntaxmeets/src/components/Navbar/Navbar.js
**This PR fixes:**
- Copy message UI #44, [Here](https://imgur.com/a/bNEvwOl) is the updated UI gif.
**Related Details**
- I implemented this using the material-ui as it is used in the project and this is better than the UI suggested by me earlier.
=> Improve copy message UI

CONTRIBUTING.md
{minor change in the GitHub command to set the upstream repository, mentioned in the Contributing.md file}
=> 📚[Docs]: Improve guidelines in CONTRIBUTING.md

backend/server/index.js, frontend/syntaxmeets/src/components/SyntaxChat/SyntaxChat.js, frontend/syntaxmeets/src/components/SyntaxRoom/SyntaxRoom.js
Added functionlity to detect which user is typing .
=> 🚀[Feat]: User is typing functionality

frontend/syntaxmeets/src/components/SyntaxChat/ParticipantsList.js, frontend/syntaxmeets/src/components/SyntaxChat/SyntaxChat.js
The Close Button is added for the Participants Box as well as the Chat Box too.
Here's the Screenshot.
Please Review it.
=> Close Button added for ChatBox and ParticipantsList

frontend/syntaxmeets/package.json, frontend/syntaxmeets/src/App.js, frontend/syntaxmeets/src/components/Loader/Loader.js, frontend/syntaxmeets/src/components/Loader/Loader.module.css, frontend/syntaxmeets/src/components/SyntaxChat/ParticipantsList.js
=> Loader component added

frontend/syntaxmeets/src/components/Footer/Footer.js, frontend/syntaxmeets/src/components/SyntaxChat/ParticipantsList.js, frontend/syntaxmeets/src/components/SyntaxChat/SyntaxChat.js, frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js, frontend/syntaxmeets/src/components/SyntaxRoom/SyntaxRoom.js
- added alt-text to images (wherever necessary)
- fixed target='_blank' vulnerability, 
- fixed react useEffect() dependencies missing warnings and tested with the socket server✔
- other minor fixes.
PS: there might be some extra whitespace added in lines because of a different document formatter. (this won't affect the working of code)
=> 🐛 [BUG:] Fixed warnings and a11y issues

backend/server/index.js, backend/server/package-lock.json, backend/server/package.json, backend/server/rateLimiter.js, frontend/syntaxmeets/package-lock.json, frontend/syntaxmeets/package.json
I have applied http headers using helmet which will protect  against DDOS attack and applied the rate limiter for 100 request in every hour which will not overload the site.
Review this and if correct then please merge it.
Thanks.
=> Improve security of website  [#75 -fixed]

frontend/syntaxmeets/package-lock.json, frontend/syntaxmeets/package.json, frontend/syntaxmeets/src/components/SyntaxChat/SyntaxChat.js
=> Add Emoji picker

frontend/syntaxmeets/src/components/SyntaxChat/SyntaxChat.js
=> ⚒️[Fix]: Emoji Icon Alignment in ChatBox

README.md
=> ⚒️[Fix]: Update Application URL and Screenshots

frontend/syntaxmeets/src/components/Home/Home.js
Fixes #50 
Using the `onKeyPress()` and `click()`, it will programmatically redirect the user to the required page on pressing Enter key
=> feat: Enter Key will submit forms

frontend/syntaxmeets/src/components/SyntaxRoom/SyntaxRoom.js
Issue: #109 
The html alert is converted to material UI snackbar.
Here are the screenshot for it.
=> Alert converted to toast

frontend/syntaxmeets/src/components/SyntaxEditor/LanguageData.js, frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js
Issue #111 
Issue is resolved.
The language changes according to the file extension
=> Language gets changed on uploading

frontend/syntaxmeets/src/App.css, frontend/syntaxmeets/src/components/SyntaxChat/ParticipantsList.js
Scrollbar-Styles Added!
Also noticed one issue ,
When we clicked on participants , we see two scrollbars 
one scrollbar would do work for scrolling participants list , so i had removed overflow-y: scroll property!
=> ⚒️[Fix]: Scrollbar Customized

frontend/syntaxmeets/src/components/About/Card/MediaCard.js
=> ⚒️[Fix]: About Creators socials Link CSS fix

frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js, frontend/syntaxmeets/src/components/SyntaxRoom/SyntaxRoom.js, frontend/syntaxmeets/src/store/actions/editorActions.js, frontend/syntaxmeets/src/store/actions/uiActions.js, frontend/syntaxmeets/src/store/reducers/uiReducer.js, frontend/syntaxmeets/src/store/types.js
Closes: #87 
Hi @kothariji
kindly review the PR, I've done the following changes:
- added a UI state in redux called `isFocusMode`
- added `toggleFocusMode()` action for toggling focus mode.
Regards ✌💯
=> 🚀[FEAT: ] Focus mode implemented

frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js
The issue #119  is solved.
Now, the snackbar is shown for the error occured instead of default alert.
=> Snackbar created

frontend/syntaxmeets/src/components/SyntaxChat/SyntaxChat.js
=> disable empty messages in chat box

frontend/syntaxmeets/src/components/About/About.module.css, frontend/syntaxmeets/src/components/About/Card/MediaCard.js
CLoses #138 
Now the cards css is fixed.
The icons are also aligned and don't go on next line while reducing the screen size.
Here are some screenshots.
=> Cards CSS fixed

frontend/syntaxmeets/src/components/SyntaxEditor/SyntaxEditor.js
Closes #148 
Here are some preview of my work.
=> Share Url Modal Created

frontend/syntaxmeets/src/components/SyntaxChat/SyntaxChat.js
=> message added
